# Generated by Django 4.2.1 on 2023-06-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='description',
            new_name='feedback',
        ),
    ]
